name: Run Vinted Scanner

on:
  schedule:
    - cron: '0 * * * *'   # Every hour at minute 0
  workflow_dispatch:       # Allows manual run from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # or whatever version you prefer

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        # add more secrets here if needed
      run: |
        python your_script.py
