name: Vinted Scanner

on:
  schedule:
    - cron: '0 * * * *'   # runs every hour
  workflow_dispatch:      # allows you to run manually from GitHub UI

jobs:
  run-vinted-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache processed items DB
        uses: actions/cache@v3
        with:
          path: processed_items.db
          key: processed-items-db-${{ runner.os }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python vinted_scanner.py

