name: Vinted Scanner

on:
  schedule:
    - cron: '0 * * * *'   # runs every hour
  workflow_dispatch:      # allows you to run manually from GitHub UI

jobs:
  run-vinted-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # or your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner script
        run: python vinted_scanner.py
