name: Vinted Scanner

on:
  schedule:
    - cron: '0 * * * *'   # every hour
  workflow_dispatch:

jobs:
  run-vinted-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python vinted_scanner.py

      - name: Commit updated DB
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add processed_items.db
          git commit -m "Update processed_items.db [skip ci]" || echo "No changes to commit"
          git push
        env:
          # needed for pushing back
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
